spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/all_extreme?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    username: "${DB_USER:root}"
    password: "${DB_PASSWORD:1234}"
#    url: "${JDBC_DATABASE_URL}"
#    username: "${JDBC_DATABASE_USERNAME}"
#    password: "${JDBC_DATABASE_PASSWORD}"
    continueOnError: true
#    driverClassName: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          facebook:
  #            client-id: 596493257866350
  #            client-secret: 94406040e61d257c47ec385fc253dc4c
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    cache:
      cachecontrol:
        max-age: 30d
    chain:
      strategy:
        content:
          enabled: true
          paths: /css/**
cloudinary:
  cloud_name: "${CLOUD_NAME}"
  api_key: "${API_KEY}"
  api_secret: "${API_SECRET}"
allExtreme:
  clean-up: "0 0 2 ? * SUN"
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

